### PR TITLE
Improve OOP: use object composition instead of inheritance

### PR DESCRIPTION
**Pull request by mtymek**
This came up when writing unit tests.

Current approach for `AlbumTable` (extending TableGateway) is not a perfect from good OOP perspective (try to write a test for current `AlbumTable` to see what I mean). 
This PR replaces inheritance with composition, making the code easier to understand and test.

@RalfEggert do you like this idea? I could make this code even more SOLID by adding interface for `AlbumTable`, but I'm not sure how far we should go, without making it too complex to understand.

### CODE REVIEW

**Comment by codeliner** [comment]
+1 for the suggestion. s/AlbumTable/AlbumRepository and it would be ++1 ;)

**Comment by mtymek** [comment]
You asked, you have it :)

**Comment by codeliner** [comment]
:+1: :+1: :smile:

**Comment by RalfEggert** [comment]
Yes, I missed the wrong usage of TableGateway. I planned to do it in the same way as it is done in the MVC album tutorial but then in the end I implemented it in a wrong way.

Regarding the repository. Yes, that is a good idea. I did not use it because I wanted to keep the code as simple as possible. I planned to explain the usefulness of a repository to give the advanced users an idea how to improve the code.

**Pull request merged**
